# Generated by Django 4.2.11 on 2024-04-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(default='2024-04-30'),
            preserve_default=False,
        ),
    ]
